// frontend/src/routes/login.tsx
import { createRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { rootRoute } from "./__root";
import { useAuth } from "../store/auth";
import { api } from "../api/client";

interface UserSuggestion {
  full_name: string;
  position: string;
  staff_id: string;
}

export const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/login",
  component: LoginPage,
});

function LoginPage() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [surname, setSurname] = useState("");
  const [staffId, setStaffId] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [suggestions, setSuggestions] = useState<UserSuggestion[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const formRef = useRef<HTMLFormElement>(null);

  const searchUsers = useCallback((q: string) => {
    if (debounceRef.current !== null) clearTimeout(debounceRef.current);
    if (q.length < 3) {
      setSuggestions([]);
      setShowSuggestions(false);
      return;
    }
    debounceRef.current = setTimeout(async () => {
      try {
        const data = await api<UserSuggestion[]>(`/api/users/search?q=${encodeURIComponent(q)}`);
        setSuggestions(data);
        setShowSuggestions(data.length > 0);
      } catch {
        setSuggestions([]);
      }
    }, 300);
  }, []);

  const selectUser = (s: UserSuggestion) => {
    setSurname(s.full_name);
    setStaffId(s.staff_id);
    setSuggestions([]);
    setShowSuggestions(false);
  };

  useEffect(() => {
    const close = (e: MouseEvent) => {
      if (formRef.current && !formRef.current.contains(e.target as Node)) {
        setShowSuggestions(false);
      }
    };
    document.addEventListener("click", close);
    return () => document.removeEventListener("click", close);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!staffId) {
      setError("Выберите пользователя из списка подсказок");
      return;
    }
    setLoading(true);
    setError("");
    try {
      const result = await login(staffId, password);
      navigate({ to: result.changePassword ? "/change-password" : "/main-afl" });
    } catch (err) {
      console.error("Login error:", err);
      setError("Неверный логин или пароль");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-[70vh]">
      <div className="card bg-base-100 shadow-xl w-full max-w-md">
        <div className="card-body">
          <h2 className="card-title text-center justify-center mb-2">MYTRA</h2>
          <p className="text-center text-base-content/50 text-sm mb-6">Управление реестрами</p>

          <form ref={formRef} onSubmit={handleSubmit} autoComplete="off">
            <div className="form-control mb-4 relative">
              <label className="label"><span className="label-text">Фамилия</span></label>
              <input
                type="text"
                placeholder="Начните вводить фамилию"
                className="input input-bordered w-full"
                value={surname}
                autoComplete="off"
                onChange={(e) => {
                  setSurname(e.target.value);
                  setStaffId("");
                  searchUsers(e.target.value);
                }}
              />
              {showSuggestions && (
                <div className="absolute top-full left-0 right-0 bg-base-100 border border-base-300 rounded-box shadow-lg z-10">
                  {suggestions.map((s) => (
                    <div
                      key={s.staff_id}
                      className="p-3 hover:bg-base-200 cursor-pointer border-b border-base-200 last:border-b-0"
                      onMouseDown={(e) => {
                        e.preventDefault();
                        selectUser(s);
                      }}
                    >
                      <div className="text-sm font-medium">{s.full_name}</div>
                      <div className="text-xs text-base-content/50">{s.position} • {s.staff_id}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="form-control mb-6">
              <label className="label"><span className="label-text">Пароль</span></label>
              <input
                type="password"
                placeholder="Введите пароль"
                className="input input-bordered w-full"
                value={password}
                autoComplete="current-password"
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            {error && <div className="alert alert-error mb-4"><span>{error}</span></div>}
            <button type="submit" className="btn btn-accent w-full" disabled={loading}>
              {loading ? <span className="loading loading-spinner" /> : "Войти"}
            </button>
          </form>

          <div className="text-center text-xs text-base-content/30 mt-4">
            Первый вход — используйте табельный номер
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-svelte/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { login } from '$lib/store/auth.svelte';
	import { api } from '$lib/api/client';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import Logo from '$lib/components/logo.svelte';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';

	interface UserSuggestion {
		full_name: string;
		position: string;
		staff_id: string;
	}

	let surname = $state('');
	let staffId = $state('');
	let password = $state('');
	let error = $state('');
	let loading = $state(false);
	let suggestions = $state<UserSuggestion[]>([]);
	let showSuggestions = $state(false);
	let timer: ReturnType<typeof setTimeout> | null = null;

	function searchUsers(q: string) {
		if (timer) clearTimeout(timer);
		if (q.length < 3) {
			suggestions = [];
			showSuggestions = false;
			return;
		}
		timer = setTimeout(async () => {
			try {
				const data = await api<UserSuggestion[]>(`/api/users/search?q=${encodeURIComponent(q)}`);
				suggestions = data;
				showSuggestions = data.length > 0;
			} catch {
				suggestions = [];
				showSuggestions = false;
			}
		}, 300);
	}

	function selectUser(s: UserSuggestion) {
		surname = s.full_name;
		staffId = s.staff_id;
		suggestions = [];
		showSuggestions = false;
	}

	function onSurname(e: Event) {
		surname = (e.target as HTMLInputElement).value;
		staffId = '';
		searchUsers(surname);
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!staffId) {
			error = 'Выберите пользователя из списка подсказок';
			return;
		}
		loading = true;
		error = '';
		try {
			const result = await login(staffId, password);
			await goto(result.changePassword ? '/change-password' : '/main-afl');
		} catch {
			error = 'Неверный логин или пароль';
		} finally {
			loading = false;
		}
	}
</script>

<div class="flex min-h-screen items-center justify-center p-4">
	<Card class="w-full max-w-md">
		<CardHeader>
			<CardTitle class="flex items-center justify-center gap-2">
				<Logo />
				<span>MYTRA</span>
			</CardTitle>
			<CardDescription class="text-center">Управление реестрами</CardDescription>
		</CardHeader>
		<CardContent>
			<form onsubmit={handleSubmit} autocomplete="off" class="space-y-4">
				<div class="relative space-y-1.5">
					<label class="text-sm font-medium" for="surname">Фамилия</label>
					<Input
						id="surname"
						type="text"
						placeholder="Начните вводить фамилию"
						value={surname}
						oninput={onSurname}
						autocomplete="off"
					/>
					{#if showSuggestions}
						<div class="absolute left-0 right-0 top-full z-10 mt-1 overflow-hidden rounded-md border bg-popover shadow-lg">
							{#each suggestions as s (s.staff_id)}
								<button
									type="button"
									class="block w-full border-b px-3 py-2 text-left transition-colors last:border-b-0 hover:bg-accent"
									onmousedown={(e) => {
										e.preventDefault();
										selectUser(s);
									}}
								>
									<div class="text-sm font-medium">{s.full_name}</div>
									<div class="text-xs text-muted-foreground">{s.position} • {s.staff_id}</div>
								</button>
							{/each}
						</div>
					{/if}
				</div>

				<div class="space-y-1.5">
					<label class="text-sm font-medium" for="password">Пароль</label>
					<Input
						id="password"
						type="password"
						placeholder="Введите пароль"
						bind:value={password}
						autocomplete="current-password"
					/>
				</div>

				{#if error}
					<p class="text-sm text-destructive">{error}</p>
				{/if}

				<Button type="submit" class="w-full" disabled={loading}>
					{loading ? 'Вход...' : 'Войти'}
				</Button>
			</form>

			<p class="mt-4 text-center text-xs text-muted-foreground">
				Первый вход — используйте табельный номер
			</p>
		</CardContent>
	</Card>
</div>
