// frontend-svelte/src/routes/(app)/change-password/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { api } from '$lib/api/client';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';

	let newPassword = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let loading = $state(false);

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (newPassword.length < 4) {
			error = 'Пароль должен быть не менее 4 символов';
			return;
		}
		if (newPassword !== confirmPassword) {
			error = 'Пароли не совпадают';
			return;
		}
		loading = true;
		error = '';
		try {
			await api('/api/change-password', {
				method: 'POST',
				body: JSON.stringify({ new_password: newPassword, confirm_password: confirmPassword })
			});
			await goto('/main-afl');
		} catch {
			error = 'Ошибка при смене пароля';
		} finally {
			loading = false;
		}
	}
</script>

<div class="h-full overflow-auto p-4">
	<div class="mx-auto max-w-md">
		<Card>
			<CardHeader>
				<CardTitle class="text-center">Смена пароля</CardTitle>
				<CardDescription class="text-center">Первый вход — задайте новый пароль</CardDescription>
			</CardHeader>
			<CardContent>
				<form onsubmit={handleSubmit} class="space-y-4">
					<div class="space-y-1.5">
						<label class="text-sm font-medium" for="new-password">Новый пароль</label>
						<Input id="new-password" type="password" bind:value={newPassword} autocomplete="new-password" />
					</div>
					<div class="space-y-1.5">
						<label class="text-sm font-medium" for="confirm-password">Подтверждение</label>
						<Input id="confirm-password" type="password" bind:value={confirmPassword} autocomplete="new-password" />
					</div>
					{#if error}
						<p class="text-sm text-destructive">{error}</p>
					{/if}
					<Button type="submit" class="w-full" disabled={loading}>
						{loading ? 'Смена...' : 'Сменить пароль'}
					</Button>
				</form>
			</CardContent>
		</Card>
	</div>
</div>

// frontend/src/routes/_authenticated/change-password.tsx
import { createRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { rootRoute } from "../__root";
import { useAuth } from "../../store/auth";
import { api } from "../../api/client";

export const changePasswordRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/change-password",
  component: ChangePasswordPage,
});

function ChangePasswordPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  if (!user) {
    navigate({ to: "/login" });
    return null;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newPassword.length < 4) {
      setError("Пароль должен быть не менее 4 символов");
      return;
    }
    if (newPassword !== confirmPassword) {
      setError("Пароли не совпадают");
      return;
    }
    setLoading(true);
    setError("");
    try {
      await api("/api/change-password", {
        method: "POST",
        body: JSON.stringify({ new_password: newPassword, confirm_password: confirmPassword }),
      });
      navigate({ to: "/main-afl" });
    } catch {
      setError("Ошибка при смене пароля");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-[70vh]">
      <div className="card bg-base-100 shadow-xl w-full max-w-md">
        <div className="card-body">
          <h2 className="card-title text-center justify-center mb-2">Смена пароля</h2>
          <p className="text-center text-base-content/50 text-sm mb-4">
            Первый вход — задайте новый пароль
          </p>
          <form onSubmit={handleSubmit}>
            <div className="form-control mb-4">
              <label className="label"><span className="label-text">Новый пароль</span></label>
              <input type="password" className="input input-bordered w-full"
                value={newPassword} onChange={(e) => setNewPassword(e.target.value)} />
            </div>
            <div className="form-control mb-6">
              <label className="label"><span className="label-text">Подтверждение</span></label>
              <input type="password" className="input input-bordered w-full"
                value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} />
            </div>
            {error && <div className="alert alert-error mb-4"><span>{error}</span></div>}
            <button type="submit" className="btn btn-accent w-full" disabled={loading}>
              {loading ? <span className="loading loading-spinner" /> : "Сменить пароль"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
