// frontend-svelte/src/routes/(app)/reports/+page.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query';
	import { toStore, fromStore } from 'svelte/store';
	import { queryClient } from '$lib/query';
	import {
		fetchFinReport,
		addToReport,
		uploadDiscrepancies,
		recheckTasks,
		startFinReportDownload,
		fetchFinReportDownloadProgress,
		fetchFinReportDownloadResult,
		type FinCardData,
		type FinReportData
	} from '$lib/api/fin-report';
	import { Button } from '$lib/components/ui/button';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { auth } from '$lib/store/auth.svelte';
	import { toast } from '$lib/store/toast.svelte';
	import ChevronDown from '@lucide/svelte/icons/chevron-down';

	const MONTHS = [
		'январь', 'февраль', 'март', 'апрель', 'май', 'июнь',
		'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'
	];

	const isAdmin = $derived(auth.user?.role === 'администратор');

	const options = (() => {
		const now = new Date();
		const opts: { value: string; label: string }[] = [];
		for (let i = 1; i <= 12; i++) {
			const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
			opts.push({
				value: `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`,
				label: MONTHS[d.getMonth()]
			});
		}
		return opts;
	})();

	let period = $state('');
	let reportOpen = $state(false);
	let expanded = $state<Set<string>>(new Set());

	const query = createQuery<FinReportData>(
		toStore(() => ({
			queryKey: ['fin-report', period],
			queryFn: () => fetchFinReport(period),
			enabled: isAdmin
		}))
	);
	const result = fromStore(query);
	const data = $derived(result.current.data);
	const loading = $derived(result.current.isPending);

	let adding = $state(false);
	let uploading = $state(false);
	let rechecking = $state(false);
	let downloading = $state(false);
	let downloadDone = $state(0);
	let downloadTotal = $state(0);

	let discrepanciesInput = $state<HTMLInputElement | undefined>(undefined);
	let recheckInput = $state<HTMLInputElement | undefined>(undefined);

	const fmtMoney = (v: number) =>
		v.toLocaleString('ru-RU', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + ' ₽';

	function periodLabel(p: string): string {
		if (!p) return 'Ещё не в отчёте';
		const [year, month] = p.split('-');
		return `Отчёт за ${MONTHS[Number(month) - 1]} ${year}`;
	}

	function selectPeriod(p: string) {
		period = p;
		reportOpen = false;
	}

	function toggleExpand(key: string) {
		const next = new Set(expanded);
		if (next.has(key)) next.delete(key);
		else next.add(key);
		expanded = next;
	}

	async function handleAdd() {
		adding = true;
		try {
			const res = await addToReport(period);
			toast(`Добавлено в отчёт ${res.period}: ${res.updated}`);
			await queryClient.invalidateQueries({ queryKey: ['fin-report', period] });
		} catch {
			toast('Ошибка добавления в отчёт');
		} finally {
			adding = false;
		}
	}

	function openDiscrepancies() {
		if (discrepanciesInput) {
			discrepanciesInput.value = '';
			discrepanciesInput.click();
		}
	}

	async function handleDiscrepanciesFile(file: File | undefined) {
		if (!file) return;
		if (!file.name.toLowerCase().endsWith('.txt')) {
			toast('Нужен файл .txt');
			return;
		}
		uploading = true;
		try {
			const res = await uploadDiscrepancies(file);
			toast(`Разногласия: обновлено ${res.updated} | не найдено ${res.not_found}`);
			await queryClient.invalidateQueries({ queryKey: ['fin-report', period] });
		} catch {
			toast('Ошибка загрузки разногласий');
		} finally {
			uploading = false;
		}
	}

	function openRecheck() {
		if (recheckInput) {
			recheckInput.value = '';
			recheckInput.click();
		}
	}

	async function handleRecheckFile(file: File | undefined) {
		if (!file) return;
		if (!file.name.toLowerCase().endsWith('.txt')) {
			toast('Нужен файл .txt');
			return;
		}
		rechecking = true;
		try {
			const res = await recheckTasks(file);
			const url = URL.createObjectURL(res.blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = 'Повторная_проверка.xlsx';
			document.body.appendChild(a);
			a.click();
			a.remove();
			URL.revokeObjectURL(url);
			toast(`Повторная проверка: обновлено ${res.updated} | не найдено ${res.not_found}`);
			await queryClient.invalidateQueries({ queryKey: ['fin-report', period] });
		} catch (e) {
			toast(e instanceof Error ? e.message : 'Ошибка повторной проверки');
		} finally {
			rechecking = false;
		}
	}

	async function handleDownload() {
		if (downloading || !period) return;
		downloading = true;
		downloadDone = 0;
		downloadTotal = 6;
		try {
			const { download_id } = await startFinReportDownload(period);
			for (;;) {
				await new Promise((r) => setTimeout(r, 400));
				const p = await fetchFinReportDownloadProgress(download_id);
				if (p.status === 'error') {
					toast(p.message || 'Ошибка формирования отчёта');
					return;
				}
				downloadDone = p.done;
				downloadTotal = p.total;
				if (p.status === 'complete') break;
			}
			const blob = await fetchFinReportDownloadResult(download_id);
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = `Отчёт_${period}.zip`;
			document.body.appendChild(a);
			a.click();
			a.remove();
			URL.revokeObjectURL(url);
		} catch {
			toast('Ошибка скачивания отчёта');
		} finally {
			downloading = false;
		}
	}

	const cards: { key: keyof FinReportData['cards']; label: string }[] = [
		{ key: 'completed', label: 'Заданий завершено' },
		{ key: 'without_reestr', label: 'Исполнено без реестров' },
		{ key: 'with_errors', label: 'Заданий с ошибками' },
		{ key: 'ready', label: 'Готово к отчёту' }
	];
</script>

{#if auth.loading}
	<div class="p-6"><Skeleton class="h-6 w-40" /></div>
{:else if !isAdmin}
	<div class="p-6 text-sm text-muted-foreground">Нет доступа</div>
{:else}
	<div class="flex h-full flex-col gap-3 overflow-auto p-3">
		<div class="flex flex-wrap items-center gap-2">
			<select
				value={period}
				onchange={(e) => selectPeriod((e.currentTarget as HTMLSelectElement).value)}
				class="h-8 rounded-md border border-input bg-background px-2 text-sm"
			>
				<option value="">Выберите период</option>
				{#each options as o (o.value)}
					<option value={o.value}>{o.label}</option>
				{/each}
			</select>

			<Button size="sm" onclick={handleAdd} disabled={adding || (period !== '' && !reportOpen)}>
				{adding ? 'Добавляем…' : 'Добавить в отчёт'}
			</Button>

			{#if period}
				<label
					class="flex cursor-pointer items-center gap-2 select-none"
					title="Разблокировать кнопку «Добавить в отчёт»"
				>
					<input type="checkbox" bind:checked={reportOpen} class="size-4" />
					<span class="text-sm">Разблокировать</span>
				</label>

				<Button variant="outline" size="sm" onclick={openDiscrepancies} disabled={uploading}>
					{uploading ? 'Обрабатываем…' : 'Разногласия'}
				</Button>

				<Button variant="outline" size="sm" onclick={openRecheck} disabled={rechecking}>
					{rechecking ? 'Проверяем…' : 'Повторная проверка'}
				</Button>

				<Button variant="outline" size="sm" onclick={handleDownload} disabled={downloading}>
					{downloading ? `Формируем… ${downloadDone}/${downloadTotal}` : 'Скачать отчёт'}
				</Button>
			{/if}

			<input
				bind:this={discrepanciesInput}
				type="file"
				accept=".txt"
				class="hidden"
				onchange={(e) => handleDiscrepanciesFile(e.currentTarget.files?.[0])}
			/>
			<input
				bind:this={recheckInput}
				type="file"
				accept=".txt"
				class="hidden"
				onchange={(e) => handleRecheckFile(e.currentTarget.files?.[0])}
			/>
		</div>

		<div class="flex gap-6">
			<div class="min-w-0 flex-1">
				{#if loading || !data}
					<div class="flex flex-wrap gap-3">
						{#each Array(4) as _}
							<Skeleton class="h-28 w-44" />
						{/each}
					</div>
				{:else}
					<div class="flex flex-wrap items-start gap-3">
						{#each cards as c (c.key)}
							{@render FinCard(c, data.cards[c.key])}
						{/each}
					</div>
				{/if}
			</div>

			<div class="w-[330px] shrink-0 self-start rounded-md border bg-card p-4">
				<div class="mb-2 text-xs font-medium text-muted-foreground">{periodLabel(period)}</div>
				{#if loading || !data}
					<Skeleton class="h-4 w-full" />
				{:else if data.work_types.length === 0}
					<div class="text-sm text-muted-foreground">
						{period ? 'Нет данных за период' : 'Все работы включены в отчёт'}
					</div>
				{:else}
					<div class="space-y-1">
						{#each data.work_types as w (w.label)}
							<div class="flex justify-between gap-2 text-sm">
								<span class="text-muted-foreground">{w.label}</span>
								<span class="font-semibold tabular-nums">{w.count.toLocaleString('ru-RU')}</span>
							</div>
						{/each}
					</div>
				{/if}
				<div class="mt-3 space-y-1 border-t pt-2 text-sm">
					<div class="flex justify-between font-semibold">
						<span>Итого</span>
						<span class="tabular-nums">{data ? fmtMoney(data.total_cost) : fmtMoney(0)}</span>
					</div>
					<div class="flex justify-between text-muted-foreground">
						<span>ПСК</span>
						<span class="tabular-nums">{data ? fmtMoney(data.cost_psk) : fmtMoney(0)}</span>
					</div>
					<div class="flex justify-between text-muted-foreground">
						<span>РЛЭ</span>
						<span class="tabular-nums">{data ? fmtMoney(data.cost_rle) : fmtMoney(0)}</span>
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}

{#snippet FinCard(def: { key: string; label: string }, card: FinCardData)}
	<div class="min-w-[170px] rounded-md border bg-card">
		<button class="w-full p-4 text-left" onclick={() => toggleExpand(def.key)}>
			<div class="text-xs text-muted-foreground">{def.label}</div>
			<div class="flex items-center gap-1 text-2xl font-semibold tabular-nums">
				{card.total.toLocaleString('ru-RU')}
				<ChevronDown
					class={`size-4 text-muted-foreground transition-transform ${expanded.has(def.key) ? 'rotate-180' : ''}`}
				/>
			</div>
			<div class="mt-1 text-sm text-muted-foreground tabular-nums">{fmtMoney(card.cost)}</div>
		</button>
		{#if expanded.has(def.key)}
			<div class="space-y-1 px-4 pb-3">
				{#if card.by_locale.length === 0}
					<div class="text-xs text-muted-foreground">Нет данных</div>
				{:else}
					{#each card.by_locale as b (b.locale)}
						<div class="flex justify-between gap-4 text-sm">
							<span class="text-muted-foreground">{b.locale}</span>
							<span class="font-semibold tabular-nums">{b.count.toLocaleString('ru-RU')}</span>
						</div>
					{/each}
				{/if}
			</div>
		{/if}
	</div>
{/snippet}

// frontend/src/routes/_authenticated/reports.tsx
import { createRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { rootRoute } from "../__root";
import { useAuth } from "../../store/auth";
import { fetchFinReport, addToReport, uploadDiscrepancies, type FinReportData, type FinCardData } from "../../api/fin-report";

export const reportsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/reports",
  component: ReportsPage,
});

const MONTHS = ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"];

function monthOptions(): { value: string; label: string }[] {
  const now = new Date();
  const opts: { value: string; label: string }[] = [];
  for (let i = 1; i <= 12; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    opts.push({
      value: `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`,
      label: MONTHS[d.getMonth()],
    });
  }
  return opts;
}

function periodLabel(period: string): string {
  if (!period) return "Ещё не в отчёте";
  const [year, month] = period.split("-");
  return `Отчёт за ${MONTHS[Number(month) - 1]} ${year}`;
}

function fmtMoney(v: number): string {
  return v.toLocaleString("ru-RU", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + " ₽";
}

function ReportsPage() {
  const { user } = useAuth();
  if (!user || user.role !== "администратор") {
    return <div className="p-6 text-base-content/60">Нет доступа</div>;
  }

  const [tab, setTab] = useState<"fin">("fin");

  return (
    <div className="flex flex-col h-[calc(100vh-68px)] p-3 gap-3">
      <div className="flex-shrink-0 card bg-base-100 shadow-sm rounded-md">
        <div className="flex border-b border-base-200">
          <button
            onClick={() => setTab("fin")}
            className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px ${
              tab === "fin" ? "border-accent text-accent" : "border-transparent text-base-content/60 hover:text-base-content"
            }`}
          >
            Финотчёт
          </button>
        </div>
      </div>

      {tab === "fin" && <FinReportTab />}
    </div>
  );
}

function FinReportTab() {
  const [options] = useState(monthOptions);
  const [period, setPeriod] = useState("");
  const [reportOpen, setReportOpen] = useState(false);
  const [data, setData] = useState<FinReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [uploadingDiscrepancies, setUploadingDiscrepancies] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const discrepanciesInput = useRef<HTMLInputElement>(null);

  const showToast = (msg: string) => {
    setToast(msg);
    if (toastTimer.current) clearTimeout(toastTimer.current);
    toastTimer.current = setTimeout(() => setToast(null), 3000);
  };

  const load = async (p: string) => {
    setLoading(true);
    try {
      setData(await fetchFinReport(p));
    } catch {
      showToast("Ошибка загрузки финотчёта");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load(period);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [period]);

  const selectPeriod = (p: string) => {
    // Смена периода всегда возвращает блок на добавление (отчёт «закрыт» по умолчанию).
    setPeriod(p);
    setReportOpen(false);
  };

  const handleToggleReport = () => {
    setReportOpen((prev) => !prev);
  };

  const openDiscrepancies = () => {
    if (discrepanciesInput.current) {
      discrepanciesInput.current.value = "";
      discrepanciesInput.current.click();
    }
  };

  const handleDiscrepanciesFile = async (file: File | undefined) => {
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".txt")) {
      showToast("Нужен файл .txt");
      return;
    }
    setUploadingDiscrepancies(true);
    try {
      const res = await uploadDiscrepancies(file);
      showToast(`Разногласия: обновлено ${res.updated} | не найдено ${res.not_found}`);
      await load(period);
    } catch {
      showToast("Ошибка загрузки разногласий");
    } finally {
      setUploadingDiscrepancies(false);
    }
  };

  const toggleExpand = (key: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const handleAdd = async () => {
    if (!period) return;
    try {
      const res = await addToReport(period);
      showToast(`Добавлено в отчёт: ${res.updated}`);
      await load(period);
    } catch {
      showToast("Ошибка добавления в отчёт");
    }
  };

  const handleDownload = async () => {
    if (downloading || !period) return;
    setDownloading(true);
    try {
      const res = await fetch(`/api/fin-report/download?period=${encodeURIComponent(period)}`, { credentials: "include" });
      if (!res.ok) {
        showToast("Ошибка скачивания отчёта");
        return;
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Отчёт_${period}.zip`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch {
      showToast("Ошибка скачивания отчёта");
    } finally {
      setDownloading(false);
    }
  };

  const cards: { key: keyof FinReportData["cards"]; label: string }[] = [
    { key: "completed", label: "Заданий завершено" },
    { key: "without_reestr", label: "Исполнено без реестров" },
    { key: "with_errors", label: "Заданий с ошибками" },
    { key: "ready", label: "Готово к отчёту" },
  ];

  return (
    <div className="flex-1 min-h-0 flex flex-col gap-3">
      <div className="flex-shrink-0 flex flex-wrap items-center gap-2">
        <select className="select select-bordered select-sm" value={period} onChange={(e) => selectPeriod(e.target.value)}>
          <option value="">Выберите период</option>
          {options.map((o) => (
            <option key={o.value} value={o.value}>{o.label}</option>
          ))}
        </select>
        <button
          className="btn btn-accent btn-sm"
          onClick={handleAdd}
          disabled={!reportOpen || !period}
          title={!reportOpen ? "Отчёт закрыт — откройте переключателем" : !period ? "Выберите период" : undefined}
        >
          Добавить в отчёт
        </button>
        <button
          className="btn btn-outline btn-sm"
          onClick={handleToggleReport}
          title={reportOpen ? "Закрыть отчёт (заблокирует «Добавить»)" : "Открыть отчёт (разблокирует «Добавить»)"}
        >
          {reportOpen ? "Закрыть отчёт" : "Открыть отчёт"}
        </button>
        <button
          className="btn btn-outline btn-sm"
          onClick={openDiscrepancies}
          disabled={uploadingDiscrepancies}
        >
          {uploadingDiscrepancies ? <span className="loading loading-spinner loading-sm" /> : null}
          {uploadingDiscrepancies ? "Обрабатываем…" : "Разногласия"}
        </button>
        <button
          className="btn btn-outline btn-sm"
          onClick={handleDownload}
          disabled={downloading || !period}
          title={period ? undefined : "Выберите период"}
        >
          {downloading ? <span className="loading loading-spinner loading-sm" /> : null}
          {downloading ? "Формируем…" : "Скачать отчёт"}
        </button>
        <input
          ref={discrepanciesInput}
          type="file"
          accept=".txt"
          className="hidden"
          placeholder="Выберите txt файл с номерами отклонённых заданий"
          title="Выберите txt файл с номерами отклонённых заданий"
          onChange={(e) => handleDiscrepanciesFile(e.target.files?.[0])}
        />
      </div>

      <div className="flex-1 min-h-0 flex gap-6">
        <div className="flex-1 min-w-0">
          {loading || !data ? (
            <div className="flex items-center justify-center h-full">
              <span className="loading loading-spinner loading-lg text-accent" />
            </div>
          ) : (
            <div className="flex flex-wrap gap-3 items-start">
              {cards.map((c) => (
                <FinCard
                  key={c.key}
                  label={c.label}
                  card={data.cards[c.key]}
                  expanded={expanded.has(c.key)}
                  onToggle={() => toggleExpand(c.key)}
                />
              ))}
            </div>
          )}
        </div>

        <div className="w-[330px] flex-shrink-0 card bg-base-100 shadow-sm rounded-md p-4 self-start">
          <div className="text-xs text-base-content/50 mb-2 font-medium">{periodLabel(period)}</div>
          {loading || !data ? (
            <span className="loading loading-spinner loading-sm text-accent" />
          ) : data.work_types.length === 0 ? (
            <div className="text-sm text-base-content/50">
              {period ? "Нет данных за период" : "Все работы включены в отчёт"}
            </div>
          ) : (
            <div className="space-y-1">
              {data.work_types.map((w) => (
                <div key={w.label} className="flex justify-between gap-2 text-sm">
                  <span className="text-base-content/70">{w.label}</span>
                  <span className="font-semibold tabular-nums">{w.count.toLocaleString("ru-RU")}</span>
                </div>
              ))}
            </div>
          )}
          <div className="border-t border-base-300 mt-3 pt-2 space-y-1 text-sm">
            <div className="flex justify-between font-semibold">
              <span>Итого</span>
              <span className="tabular-nums">{data ? fmtMoney(data.total_cost) : fmtMoney(0)}</span>
            </div>
            <div className="flex justify-between text-base-content/70">
              <span>ПСК</span>
              <span className="tabular-nums">{data ? fmtMoney(data.cost_psk) : fmtMoney(0)}</span>
            </div>
            <div className="flex justify-between text-base-content/70">
              <span>РЛЭ</span>
              <span className="tabular-nums">{data ? fmtMoney(data.cost_rle) : fmtMoney(0)}</span>
            </div>
          </div>
        </div>
      </div>

      {toast && (
        <div className="toast toast-top toast-center z-50">
          <div className="alert alert-info">{toast}</div>
        </div>
      )}
    </div>
  );
}

function FinCard({ label, card, expanded, onToggle }: { label: string; card: FinCardData; expanded: boolean; onToggle: () => void }) {
  return (
    <div className="card bg-base-100 shadow-sm rounded-md min-w-[170px]">
      <button className="w-full text-left p-4" onClick={onToggle}>
        <div className="text-xs text-base-content/50">{label}</div>
        <div className="text-2xl font-semibold tabular-nums flex items-center gap-1">
          {card.total.toLocaleString("ru-RU")}
          <span className="text-xs text-base-content/40">{expanded ? "▲" : "▼"}</span>
        </div>
        <div className="text-sm text-base-content/70 tabular-nums mt-1">{fmtMoney(card.cost)}</div>
      </button>
      {expanded && (
        <div className="px-4 pb-3 space-y-1">
          {card.by_locale.length === 0 ? (
            <div className="text-xs text-base-content/50">Нет данных</div>
          ) : (
            card.by_locale.map((b) => (
              <div key={b.locale} className="flex justify-between gap-4 text-sm">
                <span className="text-base-content/70">{b.locale}</span>
                <span className="font-semibold tabular-nums">{b.count.toLocaleString("ru-RU")}</span>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}
