// frontend/src/routes/_authenticated/main-afl.tsx
import { createRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useRef, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { rootRoute } from "../__root";
import { useAuth } from "../../store/auth";
import { useMainAfl, useMainAflStats } from "../../hooks/use-main-afl";
import { DataTable } from "../../components/table/data-table";
import type { MainAflRow, MainAflParams } from "../../api/main-afl";
import { createReestr, resetReestr, fetchReestrList, downloadReestrUrl } from "../../api/main-afl";

export const mainAflRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/main-afl",
  component: MainAflPage,
});

const columns: ColumnDef<MainAflRow>[] = [
  { accessorKey: "task_number", header: "№ задания" },
  { accessorKey: "task_source", header: "Источник" },
  { accessorKey: "task_type", header: "Вид задания" },
  { accessorKey: "work_type_in_task", header: "Поручение" },
  { accessorKey: "personal_account", header: "Точка учёта" },
  { accessorKey: "subscriber_name", header: "Потребитель" },
  { accessorKey: "address", header: "Адрес" },
  { accessorKey: "municipal_district", header: "Район" },
  { accessorKey: "house_type", header: "Тип дома" },
  { accessorKey: "service_object_type", header: "Объект" },
  { accessorKey: "meter_installation_place", header: "Место ПУ" },
  { accessorKey: "meter_status", header: "Статус" },
  { accessorKey: "meter_ownership", header: "Принадлежность" },
  { accessorKey: "violations", header: "Нарушения" },
  { accessorKey: "comment", header: "Комментарий" },
  { accessorKey: "customer", header: "Заказчик" },
  { accessorKey: "executor", header: "Исполнитель" },
  { accessorKey: "visit_reason", header: "Основание" },
  { accessorKey: "task_output", header: "Результат" },
  { accessorKey: "task_report", header: "Отчёт" },
  { accessorKey: "grid", header: "Сеть" },
  { accessorKey: "done_day", header: "Дата" },
  { accessorKey: "reestr_number", header: "Реестр" },
];


function MainAflPage() {
  const { user } = useAuth();
  const [tab, setTab] = useState<"add" | "list" | "settings">("add");
  const [params, setParams] = useState<MainAflParams>({ page: 1, per_page: 50 });
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [toast, setToast] = useState<string | null>(null);
  const [reestrs, setReestrs] = useState<string[]>([]);
  const [reestrMeta, setReestrMeta] = useState<Record<string, { task_report: string | null; customer: string | null }>>({});
  const [activeReestr, setActiveReestr] = useState<string>("");
  const [emptyReestrs, setEmptyReestrs] = useState<Set<string>>(new Set());
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const { data, isLoading, refetch } = useMainAfl(params);
  const rows = data?.rows ?? [];
  const total = data?.total ?? 0;

  const getId = useCallback((row: MainAflRow) => row.task_number ?? "", []);

  const toggleRow = useCallback((id: string) => {
    setSelected((prev) => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; });
  }, []);

  const showToast = (msg: string) => {
    setToast(msg);
    if (toastTimer.current !== null) clearTimeout(toastTimer.current);
    toastTimer.current = setTimeout(() => setToast(null), 3000);
  };

  const loadReestrs = async () => {
    const data = await fetchReestrList();
    setReestrs(data.reestrs);
    setReestrMeta(data.meta);
    if (data.reestrs.length > 0 && !activeReestr) {
      setActiveReestr(data.reestrs[0]);
    }
  };

  useEffect(() => { loadReestrs(); }, []);

  const handleCreateReestr = async () => {
    if (selected.size === 0) { showToast("Не выбраны строки"); return; }
    try {
      const result = await createReestr([...selected]);
      const parts = result.reestrs.map((r) =>
        r.reestr_number === "Отклонён" ? `${r.task_report}: отклонён` : `${r.reestr_number} — ${r.task_report} (${r.count})`
      );
      showToast(parts.join(" | ") || "Готово");
      setSelected(new Set()); refetch(); loadReestrs();
    } catch { showToast("Ошибка создания реестра"); }
  };

  const handleResetReestr = async () => {
    if (selected.size === 0) { showToast("Не выбраны строки"); return; }
    try {
      const result = await resetReestr([...selected]);
      showToast(`Сброшено: ${result.cleared}`);
      setSelected(new Set()); refetch(); loadReestrs();
    } catch { showToast("Ошибка сброса реестра"); }
  };

  const handleResetFilters = () => { setParams({ page: 1, per_page: 50 }); setSelected(new Set()); };

  const handleSelectReestr = (rn: string) => {
    setParams({ ...params, reestr: rn, page: 1 });
  };

  const toggleEmpty = (rn: string) => {
    setEmptyReestrs((prev) => { const next = new Set(prev); next.has(rn) ? next.delete(rn) : next.add(rn); return next; });
  };

  if (!user) return null;

  return (
    <div className="flex flex-col h-[calc(100vh-68px)] p-3 gap-3">
      {toast && <div className="fixed top-16 right-4 z-50 alert alert-success shadow-lg w-auto max-w-lg py-2 px-4 text-sm"><span>{toast}</span></div>}

      <div className="flex-shrink-0">
        <div className="card bg-base-100 shadow-sm rounded-md">
          <div className="flex border-b border-base-200">
            {(["add", "list", "settings"] as const).map((t) => (
              <button key={t} onClick={() => {
                setTab(t);
                if (t === "list") { loadReestrs(); setParams({ page: 1, per_page: 50, reestr: activeReestr || reestrs[0] || undefined }); }
                if (t === "add") { setParams({ page: 1, per_page: 50, reestr: undefined }); }
              }}
                className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px
                  ${tab === t ? "border-accent text-accent" : "border-transparent text-base-content/50 hover:text-base-content"}`}>
                {{ add: "Добавление", list: "Список", settings: "Настройка" }[t]}
              </button>
            ))}
          </div>

          <div className="py-2 px-3">
            {tab === "add" && <AddTab params={params} setParams={setParams} onReset={handleResetFilters} onCreate={handleCreateReestr} />}
            {tab === "list" && <ListTab reestrs={reestrs} activeReestr={activeReestr} setActiveReestr={setActiveReestr} emptyReestrs={emptyReestrs} toggleEmpty={toggleEmpty} onReset={handleResetReestr} onSelectReestr={handleSelectReestr} meta={reestrMeta} />}
            {tab === "settings" && <SettingsTab />}
          </div>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-hidden">
        {isLoading ? (
          <div className="flex justify-center py-12"><span className="loading loading-spinner loading-lg text-accent" /></div>
        ) : (
          <DataTable columns={columns} data={rows} total={total}
            page={params.page ?? 1} perPage={params.per_page ?? 50}
            selectedIds={selected} onRowClick={toggleRow}
            onSort={(sort, order) => setParams({ ...params, sort, order })}
            onPage={(page) => setParams({ ...params, page })}
            getId={getId} />
        )}
      </div>
    </div>
  );

function AddTab({ params, setParams, onReset, onCreate }: {
  params: MainAflParams; setParams: (p: MainAflParams) => void;
  onReset: () => void; onCreate: () => void;
}) {
  const { data: stats } = useMainAflStats();

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-2 items-center">
        <input type="text" placeholder="Поиск по адресу, № задания или л/с" className="input input-bordered input-sm flex-1 min-w-[220px]"
          value={params.search ?? ""} onChange={(e) => setParams({ ...params, search: e.target.value || undefined, page: 1 })} />
        <input type="text" placeholder="Дата работ" className="input input-bordered input-sm w-[140px]"
          value={(params as Record<string, string>).done_day ?? ""} onChange={(e) => setParams({ ...params, done_day: e.target.value || undefined } as MainAflParams)} />
        <button className="btn btn-ghost btn-sm" onClick={onReset}>Сброс фильтров</button>
        <button className="btn btn-accent btn-sm" onClick={onCreate}>В реестр</button>
      </div>
      <div className="border-t border-base-200" />
      <div className="grid grid-cols-3 gap-6 text-sm">
        <div>
          <div className="text-xs text-base-content/40 mb-1.5 font-medium">Статистика</div>
          <div className="flex flex-col gap-y-0.5 text-xs">
            {[
              { label: "ПСК", count: stats?.customers?.["ПСК"] },
              { label: "РЛЭ", count: stats?.customers?.["РЛЭ"] },
              { label: "План", count: stats?.plan },
              { label: "Внеплан", count: stats?.unplan },
              { label: "Выполнено", count: stats?.completed },
              { label: "Не выполнено", count: stats?.uncompleted },
              { label: "С реестром", count: stats?.with_reestr },
              { label: "Без реестра", count: stats?.without_reestr },
            ].map((s) => (
              <button key={s.label} className="text-left cursor-pointer hover:underline flex gap-1"
                onClick={() => {
                  if (s.label === "ПСК") setParams({ ...params, customer: params.customer === "ПСК" ? undefined : "ПСК", page: 1 });
                  if (s.label === "РЛЭ") setParams({ ...params, customer: params.customer === "РЛЭ" ? undefined : "РЛЭ", page: 1 });
                  if (s.label === "План") setParams({ ...params, task_type: params.task_type === "Плановый" ? undefined : "Плановый", page: 1 } as MainAflParams);
                  if (s.label === "Внеплан") setParams({ ...params, task_type: params.task_type === "Внеплановый" ? undefined : "Внеплановый", page: 1 } as MainAflParams);
                  if (s.label === "Выполнено") setParams({ ...params, only_completed: params.only_completed ? undefined : true, page: 1 });
                  if (s.label === "Не выполнено") setParams({ ...params, only_completed: undefined, page: 1 } as MainAflParams);
                  if (s.label === "С реестром") setParams({ ...params, only_without_reestr: undefined, page: 1 });
                  if (s.label === "Без реестра") setParams({ ...params, only_without_reestr: params.only_without_reestr ? undefined : true, page: 1 });
                }}>
                <span className="text-base-content/70">{s.label}</span>
                <span className="font-semibold tabular-nums ml-auto">{s.count != null ? s.count.toLocaleString() : "—"}</span>
              </button>
            ))}
          </div>
        </div>
        <div>
          <div className="text-xs text-base-content/40 mb-1.5 font-medium">По видам работ</div>
          <div className="flex flex-col gap-y-0.5 text-xs">
            {stats?.task_reports?.map((tr) => (
              <button key={tr.label} className="text-left cursor-pointer hover:underline flex gap-1"
                onClick={() => setParams({ ...params, task_report: params.task_report === (tr.label === "Не выполнено" ? undefined : tr.label) ? undefined : (tr.label === "Не выполнено" ? "" : tr.label), page: 1 } as MainAflParams)}>
                <span className="text-base-content/70">{tr.label}</span>
                <span className="font-semibold tabular-nums ml-auto">{tr.count.toLocaleString()}</span>
              </button>
            )) ?? <span className="text-base-content/50">—</span>}
          </div>
        </div>
        <div>
          <div className="text-xs text-base-content/40 mb-1.5 font-medium">По исполнителям</div>
          <div className="flex flex-col gap-y-0.5 text-xs">
            {stats?.executors?.map((ex) => (
              <button key={ex.label} className="text-left cursor-pointer hover:underline flex gap-1.5"
                onClick={() => setParams({ ...params, executor_filter: params.executor_filter === ex.label ? undefined : ex.label, page: 1 })}>
                <span className="text-base-content/70 truncate">{ex.label}</span>
                <span className="font-semibold tabular-nums ml-auto">{ex.count.toLocaleString()}</span>
              </button>
            )) ?? <span className="text-base-content/50">—</span>}
          </div>
        </div>
      </div>
    </div>
  );
}

function ListTab({ reestrs, activeReestr, setActiveReestr, emptyReestrs, toggleEmpty, onReset, onSelectReestr, meta }: {
  reestrs: string[]; activeReestr: string; setActiveReestr: (r: string) => void;
  emptyReestrs: Set<string>; toggleEmpty: (rn: string) => void; onReset: () => void;
  onSelectReestr: (rn: string) => void;
  meta: Record<string, { task_report: string | null; customer: string | null }>;
}) {
  const m = meta[activeReestr];
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-2 items-center">
        {reestrs.map((rn) => (
          <button key={rn} onClick={() => { setActiveReestr(rn); onSelectReestr(rn); }}
            className={`text-sm px-2 py-0.5 rounded ${activeReestr === rn ? "bg-accent text-accent-content" : "bg-base-200 hover:bg-base-300"}`}>
            {rn}{emptyReestrs.has(rn) ? " (П)" : ""}
          </button>
        ))}
      </div>
      <div className="flex flex-wrap gap-3 items-center">
        <button className="btn btn-ghost btn-xs" onClick={() => activeReestr && window.open(downloadReestrUrl(activeReestr), "_blank")}>Печать</button>
        <button className="btn btn-ghost btn-xs" onClick={() => activeReestr && toggleEmpty(activeReestr)}>
          {activeReestr && emptyReestrs.has(activeReestr) ? "Снять (П)" : "Пустой"}
        </button>
        <button className="btn btn-ghost btn-xs" onClick={onReset}>Удалить из реестра</button>
        {m && (
          <>
            <span className="text-xs text-base-content/40">|</span>
            <span className="text-xs text-base-content/50">Вид работ: <span className="text-base-content">{m.task_report ?? "—"}</span></span>
            <span className="text-xs text-base-content/50">Заказчик: <span className="text-base-content">{m.customer ?? "—"}</span></span>
          </>
        )}
      </div>
    </div>
  );
}

}

function SettingsTab() {
  const [cols, setCols] = useState(() => columns.map((c, i) => ({ key: (c as { accessorKey?: string }).accessorKey ?? "", label: (typeof c.header === "string" ? c.header : "") as string, visible: true, order: i })));
  const dragItem = useRef<number | null>(null);
  const dragOver = useRef<number | null>(null);
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    fetch("/api/user/settings", { credentials: "include" })
      .then((r) => r.json())
      .then((data) => {
        if (data.settings?.columns) {
          const savedCols = data.settings.columns as { key: string; visible: boolean; order: number }[];
          const merged = columns.map((c, i) => {
            const sc = savedCols.find((sc) => sc.key === (c as { accessorKey?: string }).accessorKey);
            return { key: (c as { accessorKey?: string }).accessorKey ?? "", label: (typeof c.header === "string" ? c.header : "") as string, visible: sc?.visible ?? true, order: sc?.order ?? i };
          });
          merged.sort((a, b) => a.order - b.order);
          setCols(merged);
        }
      }).catch(() => {});
  }, []);

  const save = (updated: typeof cols) => {
    if (saveTimer.current !== null) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      fetch("/api/user/settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ settings: { columns: updated.map((c) => ({ key: c.key, visible: c.visible, order: c.order })) } }),
      });
    }, 500);
  };

  const toggle = (key: string) => {
    setCols((prev) => { const next = prev.map((c) => (c.key === key ? { ...c, visible: !c.visible } : c)); save(next); return next; });
  };

  const handleDragStart = (idx: number) => { dragItem.current = idx; };
  const handleDragOver = (e: React.DragEvent, idx: number) => { e.preventDefault(); dragOver.current = idx; };
  const handleDrop = () => {
    if (dragItem.current === null || dragOver.current === null) return;
    const newCols = [...cols];
    const visOnly = newCols.filter((c) => c.visible).sort((a, b) => a.order - b.order);
    const [moved] = visOnly.splice(dragItem.current, 1);
    visOnly.splice(dragOver.current, 0, moved);
    const reordered = cols.map((c) => {
      const vi = visOnly.findIndex((v) => v.key === c.key);
      return vi >= 0 ? { ...c, order: vi } : c;
    });
    setCols(reordered);
    save(reordered);
    dragItem.current = null;
    dragOver.current = null;
  };

  const visible = cols.filter((c) => c.visible).sort((a, b) => a.order - b.order);

  return (
    <div className="space-y-2 text-sm">
      <div className="text-xs text-base-content/40 font-medium">Порядок и видимость колонок (перетащите)</div>
      <div className="flex flex-wrap gap-1.5">
        {visible.map((c, i) => (
          <div key={c.key} draggable className="flex items-center gap-1.5 px-2 py-1 bg-base-200 rounded cursor-grab active:cursor-grabbing text-xs"
            onDragStart={() => handleDragStart(i)} onDragOver={(e) => handleDragOver(e, i)} onDrop={handleDrop}>
            <span className="text-base-content/30">⠿</span>
            <input type="checkbox" className="checkbox checkbox-xs" checked={true} onChange={() => toggle(c.key)} />
            <span>{c.label}</span>
          </div>
        ))}
      </div>
      {cols.some((c) => !c.visible) && (
        <div className="flex flex-wrap gap-1">
          {cols.filter((c) => !c.visible).map((c) => (
            <button key={c.key} className="btn btn-ghost btn-xs text-xs" onClick={() => toggle(c.key)}>
              + {c.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// frontend-svelte/src/routes/(app)/main-afl/+page.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query';
	import { toStore, fromStore } from 'svelte/store';
	import {
		createTable,
		getCoreRowModel,
		getSortedRowModel,
		type ColumnDef,
		type SortingState
	} from '@tanstack/table-core';
	import { api } from '$lib/api/client';
	import {
		buildMainAflQuery,
		createReestr,
		downloadReestrUrl,
		fetchMainAflStats,
		type MainAflRow,
		type MainAflResponse,
		type MainAflStats
	} from '$lib/api/main-afl';
	import { VISIBLE_COLUMNS, EXPAND_GROUPS } from '$lib/columns';
	import {
		Table,
		TableBody,
		TableCell,
		TableHead,
		TableHeader,
		TableRow
	} from '$lib/components/ui/table';
	import { Button } from '$lib/components/ui/button';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import ChevronLeft from '@lucide/svelte/icons/chevron-left';
	import ChevronRight from '@lucide/svelte/icons/chevron-right';
	import ListChecks from '@lucide/svelte/icons/list-checks';
	import TriangleAlert from '@lucide/svelte/icons/triangle-alert';
	import Coins from '@lucide/svelte/icons/coins';
	import type { Component } from 'svelte';
	import { search } from '$lib/store/search.svelte';
	import ChevronsLeft from '@lucide/svelte/icons/chevrons-left';
	import ChevronsRight from '@lucide/svelte/icons/chevrons-right';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import Printer from '@lucide/svelte/icons/printer';
	import { queryClient } from '$lib/query';
	import { toast } from '$lib/store/toast.svelte';
	import { auth } from '$lib/store/auth.svelte';
	import { Input } from '$lib/components/ui/input';
	import Search from '@lucide/svelte/icons/search';
	import { copyText } from '$lib/clipboard';

	const HEADER_ICONS: Partial<Record<keyof MainAflRow, Component>> = {
		reestr_number: ListChecks,
		errors: TriangleAlert,
		norm: Coins
	};

	const columns: ColumnDef<MainAflRow>[] = VISIBLE_COLUMNS.map((c) => ({
		accessorKey: c.key,
		header: c.header
	}));

	const perPage = 50;
	let page = $state(1);
	let sorting = $state<SortingState>([]);
	let expanded = $state<Set<string>>(new Set());

	let searchValue = $state('');
	let debounceTimer: ReturnType<typeof setTimeout> | undefined;

	$effect(() => {
		const value = search.value;
		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(() => {
			searchValue = value;
		}, 300);
	});

	let reportOptions = $state<string[]>([]);
	let reportChoice = $state<Record<string, string>>({});

	const canChangeReport = $derived(auth.user?.role === 'администратор');

	const canSelectForReestr = $derived(
		auth.user?.role === 'менеджер' || auth.user?.role === 'оператор' || auth.user?.role === 'работник'
	);

	let selected = $state<Set<string>>(new Set());
	let done_day = $state('');
	let stats = $state<MainAflStats | null>(null);

	let customer = $state<string | undefined>(undefined);
	let taskType = $state<string | undefined>(undefined);
	let onlyCompleted = $state(false);
	let taskReport = $state<string | undefined>(undefined);
	let executorFilter = $state<string | undefined>(undefined);
	let executorOrg = $state<string | undefined>(undefined);
	let onlyWithoutReestr = $state(false);

	function toggleSelected(id: string) {
		const next = new Set(selected);
		if (next.has(id)) next.delete(id);
		else next.add(id);
		selected = next;
	}

	async function copyTask(id: string) {
		if (id) await copyText(id);
	}

	$effect(() => {
		fetchMainAflStats()
			.then((s) => (stats = s))
			.catch(() => {});
	});

	const doneDays = $derived(stats?.done_days ?? []);
	const showDepartments = $derived(
		auth.user?.role === 'администратор' || auth.user?.role === 'специалист'
	);
	const filteredTaskReports = $derived(
		(stats?.task_reports ?? []).filter(
			(t) => !['Не выполнено', 'Дубли', 'Ручная проверка'].includes(t.label)
		)
	);

	function deptLabel(d: string) {
		return d.replace(/ отделение$/, '');
	}

	function resetFilters() {
		search.value = '';
		customer = undefined;
		taskType = undefined;
		onlyCompleted = false;
		taskReport = undefined;
		executorFilter = undefined;
		executorOrg = undefined;
		onlyWithoutReestr = false;
		done_day = '';
		page = 1;
	}

	function toggleStat(label: string) {
		if (label === 'ПСК') customer = customer === 'ПСК' ? undefined : 'ПСК';
		else if (label === 'РЛЭ') customer = customer === 'РЛЭ' ? undefined : 'РЛЭ';
		else if (label === 'План') taskType = taskType === 'Плановый' ? undefined : 'Плановый';
		else if (label === 'Внеплан') taskType = taskType === 'Внеплановый' ? undefined : 'Внеплановый';
		else if (label === 'Выполнено') onlyCompleted = !onlyCompleted;
		else if (label === 'Не выполнено') onlyCompleted = false;
		page = 1;
	}

	function toggleTaskReport(label: string) {
		taskReport = taskReport === label ? undefined : label;
		page = 1;
	}

	function toggleExecutor(label: string) {
		executorFilter = executorFilter === label ? undefined : label;
		page = 1;
	}

	function toggleDept(label: string) {
		executorOrg = executorOrg === label ? undefined : label;
		page = 1;
	}

	async function handleCreateReestr() {
		if (selected.size === 0) {
			toast('Не выбраны строки');
			return;
		}
		try {
			const result = await createReestr([...selected]);
			const parts = result.reestrs.map((r) =>
				r.reestr_number === 'Отклонён'
					? `${r.task_report}: отклонён`
					: `${r.reestr_number} — ${r.task_report} (${r.count})`
			);
			const blockedMsg = result.blocked?.length ? ` | Стоп-фактор: ${result.blocked.length}` : '';
			toast((parts.join(' | ') || 'Готово') + blockedMsg);
			selected = new Set();
			queryClient.invalidateQueries({ queryKey: ['main-afl'] });
		} catch {
			toast('Ошибка создания реестра');
		}
	}

	$effect(() => {
		api<string[]>('/api/task-reports')
			.then((list) => (reportOptions = list))
			.catch(() => {});
	});

	const sortKey = $derived(sorting[0]?.id ?? '');
	const sortOrder = $derived(sorting[0]?.desc ? 'desc' : 'asc');

	const query = createQuery<MainAflResponse>(
		toStore(() => ({
			queryKey: [
				'main-afl',
				page,
				sortKey,
				sortOrder,
				searchValue,
				done_day,
				customer,
				taskType,
				onlyCompleted,
				taskReport,
				executorFilter,
				executorOrg,
				onlyWithoutReestr
			],
			queryFn: () =>
				api<MainAflResponse>(
					`/api/main-afl?${buildMainAflQuery({
						page,
						per_page: perPage,
						sort: sortKey || undefined,
						order: sortKey ? sortOrder : undefined,
						search: searchValue || undefined,
						done_day: done_day || undefined,
						customer,
						task_type: taskType,
						only_completed: onlyCompleted || undefined,
						task_report: taskReport,
						executor_filter: executorFilter,
						executor_org: executorOrg,
						only_without_reestr: onlyWithoutReestr || undefined
					})}`
				)
		}))
	);

	const result = fromStore(query);
	const rows = $derived(result.current.data?.rows ?? []);
	const isPending = $derived(result.current.isPending);

	const visibleIds = $derived(rows.map((r) => r.task_number).filter(Boolean) as string[]);
	const allVisibleSelected = $derived(
		visibleIds.length > 0 && visibleIds.every((id) => selected.has(id))
	);

	function toggleAllVisible() {
		const next = new Set(selected);
		if (allVisibleSelected) {
			for (const id of visibleIds) next.delete(id);
		} else {
			for (const id of visibleIds) next.add(id);
		}
		selected = next;
	}

	const table = $derived(
		createTable({
			data: rows,
			columns,
			onStateChange: () => {},
			renderFallbackValue: null,
			getCoreRowModel: getCoreRowModel(),
			getSortedRowModel: getSortedRowModel(),
			manualSorting: true,
			manualPagination: true,
			state: { sorting }
		})
	);

	const total = $derived(result.current.data?.total ?? 0);
	const totalPages = $derived(Math.max(1, Math.ceil(total / perPage)));

	function setSort(key: string) {
		const current = sorting[0];
		if (current?.id === key) {
			if (current.desc) sorting = [];
			else sorting = [{ id: key, desc: true }];
		} else {
			sorting = [{ id: key, desc: false }];
		}
	}

	function sortIndicator(key: string) {
		const current = sorting[0];
		if (current?.id !== key) return '';
		return current.desc ? ' ↓' : ' ↑';
	}

	function toggleExpanded(id: string) {
		const next = new Set(expanded);
		if (next.has(id)) next.delete(id);
		else next.add(id);
		expanded = next;
	}

	function goToPage(p: number) {
		if (p >= 1 && p <= totalPages) page = p;
	}

	function pageItems(current: number, total: number): (number | '…')[] {
		if (total <= 1) return [1];
		const neighbors = new Set<number>([1, total]);
		for (let i = current - 2; i <= current + 2; i++) {
			if (i >= 1 && i <= total) neighbors.add(i);
		}
		const sorted = [...neighbors].sort((a, b) => a - b);
		const result: (number | '…')[] = [];
		let prev = 0;
		for (const n of sorted) {
			if (n - prev > 1) result.push('…');
			result.push(n);
			prev = n;
		}
		return result;
	}

	async function resetReestr(row: MainAflRow) {
		const tn = row.task_number;
		if (!tn) return;
		try {
			await api<{ cleared: number }>('/api/reestr/reset', {
				method: 'POST',
				body: JSON.stringify({ task_numbers: [tn] })
			});
			toast('Удалено из реестра');
			queryClient.invalidateQueries({ queryKey: ['main-afl'] });
		} catch {
			toast('Ошибка');
		}
	}

	async function changeReport(row: MainAflRow) {
		const tn = row.task_number;
		if (!tn) return;
		const chosen = reportChoice[tn];
		if (!chosen) return;
		try {
			await api('/api/main-afl/task-report', {
				method: 'PATCH',
				body: JSON.stringify({ task_numbers: [tn], task_report: chosen === '__none__' ? '' : chosen })
			});
			toast('Вид работ изменён');
			queryClient.invalidateQueries({ queryKey: ['main-afl'] });
		} catch {
			toast('Ошибка');
		}
	}
</script>

<div class="flex h-full flex-col gap-3 p-3">
	<div class="shrink-0 space-y-3">
		<div class="rounded-md border bg-card p-3">
			<div class="flex flex-wrap items-center gap-3">
				<div class="relative w-full max-w-sm">
					<Search class="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
					<Input bind:value={search.value} placeholder="Поиск по адресу, № задания или л/с" class="bg-background pl-8" />
				</div>
				<select
					class="h-9 rounded-md border border-input bg-background px-2 text-sm outline-none focus-visible:border-ring"
					bind:value={done_day}
				>
					<option value="">Выберите дату</option>
					{#each doneDays as d (d)}
						<option value={d}>{d}</option>
					{/each}
				</select>
				<label class="flex cursor-pointer items-center gap-2 text-sm">
					<button
						type="button"
						role="switch"
						aria-checked={onlyWithoutReestr}
						aria-label={onlyWithoutReestr ? 'Без реестра' : 'Все строки'}
						class={onlyWithoutReestr
							? 'relative h-5 w-9 shrink-0 rounded-full bg-primary transition-colors'
							: 'relative h-5 w-9 shrink-0 rounded-full bg-border transition-colors'}
						onclick={() => (onlyWithoutReestr = !onlyWithoutReestr)}
					>
						<span class={`absolute left-0.5 top-0.5 size-4 rounded-full bg-white shadow-sm transition-transform ${onlyWithoutReestr ? 'translate-x-4' : ''}`}></span>
					</button>
					<span class="w-24 shrink-0">{onlyWithoutReestr ? 'Без реестра' : 'Все строки'}</span>
				</label>
				{#if canSelectForReestr}
					<Button size="sm" onclick={handleCreateReestr} disabled={selected.size === 0}>
						В реестр
					</Button>
				{/if}
				<Button variant="outline" size="sm" onclick={resetFilters}>Сброс фильтров</Button>
			</div>
		</div>
		<div class="rounded-md border bg-card p-3">
			<div class="grid grid-cols-1 gap-6 text-sm sm:grid-cols-3">
				<div>
					<div class="mb-1.5 text-xs font-medium text-muted-foreground">Статистика</div>
					<div class="flex flex-col gap-y-0.5 text-xs">
						{#each [
							{ label: 'ПСК', count: stats?.customers?.['ПСК'] },
							{ label: 'РЛЭ', count: stats?.customers?.['РЛЭ'] },
							{ label: 'План', count: stats?.plan },
							{ label: 'Внеплан', count: stats?.unplan },
							{ label: 'Выполнено', count: stats?.completed },
							{ label: 'Не выполнено', count: stats?.uncompleted }
						] as s (s.label)}
							<button class="flex cursor-pointer gap-1 text-left hover:underline" onclick={() => toggleStat(s.label)}>
								<span class="text-muted-foreground">{s.label}</span>
								<span class="ml-auto font-semibold tabular-nums">{s.count != null ? s.count.toLocaleString('ru-RU') : '—'}</span>
							</button>
						{/each}
					</div>
				</div>
				<div>
					<div class="mb-1.5 text-xs font-medium text-muted-foreground">Вид работ</div>
					<div class="flex flex-col gap-y-0.5 text-xs">
						{#each filteredTaskReports as tr (tr.label)}
							<button class="flex cursor-pointer gap-1 text-left hover:underline" onclick={() => toggleTaskReport(tr.label)}>
								<span class="text-muted-foreground">{tr.label}</span>
								<span class="ml-auto font-semibold tabular-nums">{tr.count.toLocaleString('ru-RU')}</span>
							</button>
						{/each}
					</div>
				</div>
				{#if showDepartments}
					<div>
						<div class="mb-1.5 text-xs font-medium text-muted-foreground">Отделения</div>
						<div class="flex flex-col gap-y-0.5 text-xs">
							{#each stats?.depts ?? [] as d (d.label)}
								<button class="flex cursor-pointer gap-1 text-left hover:underline" onclick={() => toggleDept(d.label)}>
									<span class="text-muted-foreground">{deptLabel(d.label)}</span>
									<span class="ml-auto font-semibold tabular-nums">{d.count.toLocaleString('ru-RU')}</span>
								</button>
							{/each}
						</div>
					</div>
				{:else}
					<div>
						<div class="mb-1.5 text-xs font-medium text-muted-foreground">Исполнители</div>
						<div class="flex flex-col gap-y-0.5 text-xs">
							{#each stats?.executors ?? [] as ex (ex.label)}
								<button class="flex cursor-pointer gap-1 text-left hover:underline" onclick={() => toggleExecutor(ex.label)}>
									<span class="text-muted-foreground">{ex.label}</span>
									<span class="ml-auto font-semibold tabular-nums">{ex.count.toLocaleString('ru-RU')}</span>
								</button>
							{/each}
						</div>
					</div>
				{/if}
			</div>
		</div>
	</div>
	<div class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-md border bg-card">
		<Table containerClass="min-h-0 flex-1 overflow-auto">
				<TableHeader>
					<TableRow class="hover:bg-transparent">
						<TableHead class="sticky top-0 z-10 w-8 bg-muted text-center">
							<input
								type="checkbox"
								class="size-4 cursor-pointer accent-primary"
								checked={allVisibleSelected}
								onchange={toggleAllVisible}
							/>
						</TableHead>
						{#each VISIBLE_COLUMNS as col (col.key)}
							{@const Icon = HEADER_ICONS[col.key]}
							<TableHead
								class="sticky top-0 z-10 cursor-pointer select-none whitespace-nowrap bg-muted text-center"
								onclick={() => setSort(col.key)}
							>
								{#if Icon}
									<span class="inline-flex items-center justify-center" title={col.header}>
										<Icon class="size-4" />
									</span>
								{:else}
									{col.header}
								{/if}
								{sortIndicator(col.key)}
							</TableHead>
						{/each}
					</TableRow>
				</TableHeader>
				<TableBody>
					{#if isPending}
						{#each Array(8) as _}
							<TableRow>
								<TableCell><Skeleton class="h-4 w-4" /></TableCell>
								{#each VISIBLE_COLUMNS as _}
									<TableCell><Skeleton class="h-4 w-full" /></TableCell>
								{/each}
							</TableRow>
						{/each}
					{:else if rows.length === 0}
						<TableRow>
							<TableCell colspan={VISIBLE_COLUMNS.length + 1} class="h-24 text-center text-muted-foreground">
								Нет данных
							</TableCell>
						</TableRow>
					{:else}
						{#each table.getRowModel().rows as row (row.id)}
							{@const id = row.original.task_number ?? ''}
							<TableRow
								class="cursor-pointer"
								title="ПКМ — скопировать номер задания"
								onclick={() => toggleExpanded(id)}
								oncontextmenu={(e) => {
									e.preventDefault();
									copyTask(id);
								}}
							>
								<TableCell class="w-8 text-center" onclick={(e) => e.stopPropagation()}>
									<input
										type="checkbox"
										class="size-4 cursor-pointer accent-primary"
										checked={selected.has(id)}
										onchange={() => toggleSelected(id)}
									/>
								</TableCell>
								{#each row.getAllCells() as cell (cell.id)}
									<TableCell class={cell.column.id === 'norm' ? 'whitespace-nowrap text-center text-sm' : 'whitespace-nowrap text-sm'}>
										{#if cell.column.id === 'reestr_number'}
											{#if cell.getValue() === 'Отклонён'}
												<span class="font-bold text-brand-reestr-rejected">Р</span>
											{:else if cell.getValue()}
												<span class="font-bold text-brand-brown">Р</span>
											{:else}
												-
											{/if}
										{:else if cell.column.id === 'errors'}
											{#if cell.getValue()}
												<span class="font-bold text-destructive">О</span>
											{:else}
												-
											{/if}
										{:else}
											{cell.getValue() ?? ''}
										{/if}
									</TableCell>
								{/each}
							</TableRow>
							{#if expanded.has(id)}
								<TableRow class="bg-muted hover:bg-muted">
									<TableCell colspan={VISIBLE_COLUMNS.length + 1}>
										<div class="grid grid-cols-1 gap-x-6 gap-y-4 py-2 sm:grid-cols-2 lg:grid-cols-4">
											{#each EXPAND_GROUPS as group (group.title)}
												<div class="space-y-2">
													{#each group.columns as c (c.key)}
														<div class="text-sm">
															<span class="text-muted-foreground">{c.header}:</span>{' '}
															<span>{row.original[c.key] || '-'}</span>
														</div>
													{/each}
												</div>
											{/each}
										</div>
										<div class="mt-3 flex flex-wrap items-center gap-2 border-t pt-3">
											{#if row.original.reestr_number && row.original.reestr_number !== 'Отклонён'}
												<Button
													size="sm"
													variant="destructive"
													onclick={() => resetReestr(row.original)}
												>
													<Trash2 class="size-4" />
													Удалить из реестра
												</Button>
											{#if canSelectForReestr}
												<Button
													size="sm"
													variant="outline"
													onclick={() => window.open(downloadReestrUrl(row.original.reestr_number!), '_blank')}
												>
													<Printer class="size-4" />
													Печать реестра
												</Button>
											{/if}

											{/if}
											{#if canChangeReport}
												<select
													class="h-8 rounded-md border border-input bg-transparent px-2 text-sm outline-none focus-visible:border-ring"
													value={reportChoice[id] ?? ''}
													onchange={(e) =>
														(reportChoice[id] = (e.currentTarget as HTMLSelectElement).value)}
												>
													<option value="" disabled>Заменить вид работ</option>
													<option value="__none__">Не выполнено</option>
													{#each reportOptions as r (r)}
														<option value={r}>{r}</option>
													{/each}
												</select>
												<Button
													size="sm"
													variant="default"
													disabled={!reportChoice[id]}
													onclick={() => changeReport(row.original)}
												>
													Заменить
												</Button>
											{/if}
										</div>
									</TableCell>
								</TableRow>
							{/if}
						{/each}
					{/if}
				</TableBody>
			</Table>
	</div>

	<div class="flex items-center justify-between gap-3">
		<span class="text-sm text-muted-foreground">
			Всего: {total.toLocaleString('ru-RU')}
			{#if selected.size > 0}
				· Выбрано: {selected.size}
			{/if}
		</span>
		<div class="flex flex-wrap items-center gap-1">
			<Button variant="outline" size="sm" disabled={page <= 1} onclick={() => goToPage(1)} aria-label="Первая страница">
				<ChevronsLeft class="size-4" />
			</Button>
			<Button variant="outline" size="sm" disabled={page <= 1} onclick={() => goToPage(page - 1)} aria-label="Назад">
				<ChevronLeft class="size-4" />
			</Button>
			{#each pageItems(page, totalPages) as item, i (i)}
				{#if item === '…'}
					<span class="px-1 text-sm text-muted-foreground">…</span>
				{:else}
					<Button
						variant={item === page ? 'default' : 'outline'}
						size="sm"
						onclick={() => goToPage(item)}
					>
						{item}
					</Button>
				{/if}
			{/each}
			<Button variant="outline" size="sm" disabled={page >= totalPages} onclick={() => goToPage(page + 1)} aria-label="Вперёд">
				<ChevronRight class="size-4" />
			</Button>
			<Button variant="outline" size="sm" disabled={page >= totalPages} onclick={() => goToPage(totalPages)} aria-label="Последняя страница">
				<ChevronsRight class="size-4" />
			</Button>
		</div>
	</div>
</div>
